Rendering for glossary, including term ids, and numrefs
hsorby/vue-sphinx-xml pull request #11
Opened 2021-02-01 22:41 UTC by kerimoyle

- Renderer added for the glossary blocks, including adding an `id` term to the first of the definitions so that the hashed bookmarks (from the `<term>` blocks elsewhere) can scroll to the definition.
- Renderer added for links defined using the `numref` directive in rst, or the `<number_reference>` blocks in xml.

2021-02-01 23:01 UTC, hsorby reviewed
A couple of minor comments but it looks good.

2021-02-01 23:01 UTC, hsorby commented on src/components/templates/Term.vue
> +        class: this.classes
I'm not sure if this is doing anything.

2021-02-01 23:54 UTC, kerimoyle commented on src/components/templates/Term.vue
> +        class: this.classes
The classes could be skipped, but the attributes are what contain the ids, which are needed.  The glossary definitions work with a url with a hashed bookmark.  Unless you use this, then the ids do not make it into the html, so the hashes don't go anywhere.  Passing the ids as attributes like this means that they function correctly.

2021-02-01 23:57 UTC, hsorby commented on src/components/templates/Term.vue
> +        class: this.classes
I was specifically asking about just that single line `class: this.classes` which just appears to add an empty `class` attribute into the rendered document.  If it does indeed do nothing then it should be removed.

2021-02-02 00:02 UTC, kerimoyle commented on src/mixins/SphinxChildren.js
> +        // Do nothing: ignore this type and its children.
It's within the glossary.  It looks like something that's interpreted by js or something in other implementations, but I haven't gone through it in detail, since it wasn't needed here.  In the ones I've encountered so far there are no children.

```
        <glossary>
            <definition_list classes="glossary">
                <definition_list_item>
                    <term ids="term-C">C++<index entries="['single',\ 'C++',\ 'term-C',\ 'main',\ None]"></index></term>
                    <definition>
                        <paragraph>The language in which libCellML is written.</paragraph>
                    </definition>
                </definition_list_item>
```

2021-02-02 00:28 UTC, kerimoyle commented on src/components/templates/Term.vue
> +        class: this.classes
cf1d85f

2021-02-02 00:31 UTC, hsorby requested changes

2021-02-02 00:31 UTC, hsorby commented on src/index.js
> +  NumberReference ||
I think `Glossary` is missing from here?

2021-02-02 01:06 UTC, kerimoyle commented on src/index.js
> +  NumberReference ||
df2ef4d

2021-02-02 01:06 UTC, kerimoyle commented on src/index.js
> +  NumberReference ||
I've added it ... strange that it works without it?  I don't quite follow what this bit of the code is actually doing ...

2021-02-02 02:27 UTC, hsorby commented on src/index.js
> +  NumberReference ||
It drags all the bits together to make sure they are complete I think only a problem when you build the library and not use it as we do from links.  My understanding here is incomplete that is the best I can offer at this moment.

2021-02-02 02:28 UTC, merged